version: '3'

services:
  erp:
    container_name: "erp"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: jdbc:postgresql://fiap-lanchonete-api-erp-postgres-1:5435/erp
      SERVER_PORT: 83
    ports:
      - "83:83"
    depends_on:
      - postgres
    networks:
      - fiap-lanchonete-api-customer-totem_shared

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: erp
    expose:
      - "5435"
    ports:
      - "5435:5435"
    command: -p 5435
    networks:
      - fiap-lanchonete-api-customer-totem_shared

networks:
  fiap-lanchonete-api-customer-totem_shared:
    external: true